-- SEMANA 1 (EJEMPL)
/*CREACION DEL DEM-2 MATRICULA Y SUS TABLAS RELACIONALES */

--BD (SIN DEFINICION)
CREATE DATABASE DEMO_2_MATRICULA
GO
USE DEMO_2_MATRICULA

--CREAR TABLA DISTRITO
CREATE TABLE DISTRITO (
ID_DISTRITO CHAR(4) NOT NULL PRIMARY KEY,
NOMBRE_DISTRITO VARCHAR(40) NOT NULL,
)
GO
--CREAR TABLA ALUMNO
CREATE TABLE ALUMNO(
COD_ALUMNO INT NOT NULL PRIMARY KEY,
NOMBRE_ALU VARCHAR(40) NOT NULL,
APE_PATER_ALUM VARCHAR(40) NOT NULL,
APE_MATER_ALUM VARCHAR(40) NOT NULL,
DIRECCION VARCHAR(60) NOT NULL,
CORREO VARCHAR(80) NOT NULL,
FECHA_NACI DATE NOT NULL,
EDAD INT NOT NULL,
SEXO CHAR(1) NOT NULL,
TELEFONO CHAR(9) NOT NULL,
ID_DISTRITO CHAR(4) NOT NULL
)
GO
--CREAR TABLA CURSO
CREATE TABLE CURSO(
ID_CURSO INT NOT NULL PRIMARY KEY,
CREDITOS INT NOT NULL,
FECHA_INI_CURSO DATE NOT NULL,
FECHA_FIN_CURSO DATE NOT NULL,
NOMBRE_CURSO VARCHAR(50) NOT NULL,
DETALLE_CURSO VARCHAR(100) NOT NULL,
)
GO
--CREAR TABLA ASIGNACION
CREATE TABLE ASIGNACION(
ID_ASIGNACION INT NOT NULL PRIMARY KEY,
FECHA_ASIG DATE NOT NULL,
ID_CURSO INT NOT NULL,
)
GO
--CREAR TABLA 
CREATE TABLE PAGO (
ID_PAGO INT NOT NULL,
MONTO MONEY NOT NULL,
DESCUENTO MONEY NOT NULL,
IGV MONEY NOT NULL,
DESCRIPCION_PAGO VARCHAR(100) NOT NULL,
ID_MATRICULA INT NOT NULL,
PRIMARY KEY (ID_PAGO),
)
GO
--CREAR TABLA MATRICULA
CREATE TABLE MATRICULA(
ID_MATRICULA INT NOT NULL PRIMARY KEY,
FECHA_MATRICULA DATE NOT NULL,
ID_ALUMNO INT NOT NULL,
ID_ASIGNACION INT NOT NULL,
)
GO
--CREAR TABLA NOTA
CREATE TABLE NOTA(
ID_NOTA INT NOT NULL PRIMARY KEY,
N_PRACTICA DECIMAL(2,2) NOT NULL,
EXAMEN_PARCIAL DECIMAL(2,2) NOT NULL,
EXAMEN_FINAL DECIMAL(2,2) NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
ID_MATRICULA INT NOT NULL
)

--RELACION DE LA TABLA ALUMNO & DISTRITO
ALTER TABLE ALUMNO
ADD CONSTRAINT FK_DISTRITO_ALUMNO
FOREIGN KEY (ID_DISTRITO)
REFERENCES DISTRITO (ID_DISTRITO)

--RELACION DE LA TABLA CURSO & ASIGNACION
ALTER TABLE ASIGNACION
ADD CONSTRAINT FK_CURSO_ASIGNACION
FOREIGN KEY ([ID_CURSO])
REFERENCES CURSO([ID_CURSO])

--RELACION DE LA TABLA MATRICULA & ASIGNACION
ALTER TABLE MATRICULA
ADD CONSTRAINT FK_ASIGNACION_MATRICULA
FOREIGN KEY ([ID_ASIGNACION])
REFERENCES ASIGNACION([ID_ASIGNACION])

--RELACION DE TABLA MATRICULA & NOTA
ALTER TABLE NOTA
ADD CONSTRAINT FK_MATRICULA_NOTA
FOREIGN KEY ([ID_MATRICULA])
REFERENCES MATRICULA([ID_MATRICULA])

--CREAR TABLA DE MATRICULA & ALUMNO
ALTER TABLE ALUMNO
ADD CONSTRAINT FK_MATRICULA_ALUMNO
FOREIGN KEY ([ID_ALUMNO])
REFERENCES ALUMNO([ID_ALUMNO])

--RELACION DE LA TABLA MATRICULA & PAGO
ALTER TABLE PAGO
ADD CONSTRAINT FK_MATRICULA_PAGO
FOREIGN KEY ([ID_MATRICULA])
REFERENCES MATRICULA([ID_MATRICULA])
