--CREACION DE LA BD
USE MASTER
GO
CREATE DATABASE CODIGOSOBRERUEDAS
GO
USE CODIGOSOBRERUEDAS
GO

--CREACION DE TABLAS
--STAFF
CREATE TABLE STAFF(
ID_STAFF CHAR(5) NOT NULL PRIMARY KEY,
NAME_STAFF VARCHAR(80) NOT NULL UNIQUE,
QUANTITY INT,
)
GO
--LEVEL
CREATE TABLE LEVELL(
ID_LEVEL CHAR(5) NOT NULL PRIMARY KEY,
NAME_LEVEL VARCHAR(20) NOT NULL,
)
GO
--USER
CREATE TABLE USS (
ID_USER CHAR(5) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(200) UNIQUE NOT NULL,
PASSWORD VARCHAR (20) NOT NULL,
DNI CHAR(7) UNIQUE NOT NULL,
CELL_PHONE_NUMBER CHAR(9) NOT NULL,
ADDRESS VARCHAR (150) NOT NULL,
ID_LEVEL CHAR(5) NOT NULL REFERENCES LEVELL
)
GO
--STAFF_USER
CREATE TABLE STAFF_USER (
ID_STAFF_USER CHAR(5) NOT NULL PRIMARY KEY,
QUANTITY INT,
ID_USER CHAR(5) NOT NULL REFERENCES USS,
ID_STAFF CHAR(5) NOT NULL REFERENCES STAFF
)
GO
--PROFESSOR
CREATE TABLE PROFESSOR (
ID_PROFESSOR CHAR(5) NOT NULL PRIMARY KEY,
ID_USER CHAR(5) NOT NULL REFERENCES USS
)
GO
--TYPE_USER
CREATE TABLE TYPE_USER(
ID_TYPE_USER CHAR(5) NOT NULL PRIMARY KEY,
NAME_TYPE VARCHAR(80) NOT NULL UNIQUE,
ID_USER CHAR(5) NOT NULL REFERENCES USS
)
GO
--ENROLLMENT
CREATE TABLE ENROLLMENT (
ID_ENROLL CHAR(5) NOT NULL PRIMARY KEY,
QUANTITY INT,
IMPAIRMENT CHAR(1),
)
GO
--CODER
CREATE TABLE CODER(
ID_CODER CHAR(5) NOT NULL PRIMARY KEY,
ID_USER CHAR(5) NOT NULL REFERENCES USS,
ID_ENROLL CHAR(5) NOT NULL REFERENCES ENROLLMENT
)
--COURSE
CREATE TABLE COURSE(
ID_COURSE CHAR(5) NOT NULL PRIMARY KEY,
NAME_COURSE VARCHAR(80) NOT NULL,
ID_PROFESSOR CHAR(5) NOT NULL REFERENCES PROFESSOR,
)
GO
--CATEGORY
CREATE TABLE CATEGORY(
ID_CATEGORY CHAR(5) NOT NULL PRIMARY KEY,
NAME_CATEGORY VARCHAR(80) NOT NULL,
ID_COURSE CHAR(5) NOT NULL REFERENCES COURSE
)
GO
--SCHEDULE
CREATE TABLE SCHEDULE(
ID_SCHEDULE CHAR(5) NOT NULL PRIMARY KEY,
START_HOUR TIME NOT NULL,
END_HOUR TIME NOT NULL,
DATE_START DATE NOT NULL,
DATE_END DATE NOT NULL,
)
--COURSE_SCHEDULE
CREATE TABLE COURSE_SCHEDULE(
ID_COURSE_SCHEDULE CHAR(5) NOT NULL PRIMARY KEY,
ID_COURSE CHAR(5) NOT NULL REFERENCES COURSE,
ID_SCHEDULE CHAR(5) NOT NULL REFERENCES SCHEDULE
)
GO



