--CREACION DE LA BD
USE MASTER
GO
CREATE DATABASE CODIGOSOBRERUEDAS
GO
USE CODIGOSOBRERUEDAS
GO

--CREACION DE TABLAS
--STAFF:AREA
CREATE TABLE STAFF(
ID_STAFF CHAR(5) NOT NULL PRIMARY KEY,
NAME_STAFF VARCHAR(80) NOT NULL UNIQUE,
QUANTITY INT,
)
GO
--LEVEL:NIVEL
CREATE TABLE LEVELL(
ID_LEVEL CHAR(5) NOT NULL PRIMARY KEY,
NAME_LEVEL VARCHAR(20) NOT NULL,
)
GO
--USER:USUARIO
CREATE TABLE USS (
ID_USER CHAR(5) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(200) UNIQUE NOT NULL,
PASSWORD VARCHAR (20) NOT NULL,
DNI CHAR(7) UNIQUE NOT NULL,
CELL_PHONE_NUMBER CHAR(9) NULL,
ADDRESS VARCHAR (150) NOT NULL,
ID_LEVEL CHAR(5) NOT NULL REFERENCES LEVELL
)
GO
--STAFF_USER: AREA-USUARIO 
CREATE TABLE STAFF_USER (
ID_STAFF_USER CHAR(5) NOT NULL PRIMARY KEY,
QUANTITY INT,
ID_USER CHAR(5) NOT NULL REFERENCES USS,
ID_STAFF CHAR(5) NOT NULL REFERENCES STAFF
)
GO
--PROFESSOR: DOCENTE
CREATE TABLE PROFESSOR (
ID_PROFESSOR CHAR(5) NOT NULL PRIMARY KEY,
ID_USER CHAR(5) NOT NULL REFERENCES USS
)
GO
--TYPE_USER: TIPO DE USUARIO
CREATE TABLE TYPE_USER(
ID_TYPE_USER CHAR(5) NOT NULL PRIMARY KEY,
NAME_TYPE VARCHAR(80) NOT NULL UNIQUE,
ID_USER CHAR(5) NOT NULL REFERENCES USS
)
GO
--ENROLLMENT: INSCRIPCION
CREATE TABLE ENROLLMENT (
ID_ENROLL CHAR(5) NOT NULL PRIMARY KEY,
QUANTITY INT NULL,
)
GO
--PROGRAM : PROGRAMA
CREATE TABLE PROGRAM (
ID_PROGRAM CHAR(5) NOT NULL PRIMARY KEY,
DURATION INT NOT NULL,
TITLE VARCHAR(250) NULL,
QUANTITY INT NULL,
CHECK (QUANTITY BETWEEN 1 AND 20)

)
GO
--CODER:ALUMNO
CREATE TABLE CODER(
ID_CODER CHAR(5) NOT NULL PRIMARY KEY,
ID_USER CHAR(5) NOT NULL REFERENCES USS,
ID_ENROLL CHAR(5) NOT NULL REFERENCES ENROLLMENT,
ID_PROGRAM CHAR(5) NOT NULL REFERENCES PROGRAM,
IMPAIRMENT CHAR(1) NULL
)
GO
--SCHEDULE:HORARIO
CREATE TABLE SCHEDULE(
ID_SCHEDULE CHAR(5) NOT NULL PRIMARY KEY,
START_HOUR TIME NOT NULL,
END_HOUR TIME NOT NULL,
DATE_START DATE NOT NULL,
DATE_END DATE NOT NULL,
ID_PROGRAM CHAR(5) NOT NULL REFERENCES PROGRAM
)
GO
--COURSE:CURSO
CREATE TABLE COURSE(
ID_COURSE CHAR(5) NOT NULL PRIMARY KEY,
NAME_COURSE VARCHAR(80) NOT NULL,
ID_PROFESSOR CHAR(5) NOT NULL REFERENCES PROFESSOR,
ID_SCHEDULE CHAR(5) NOT NULL REFERENCES SCHEDULE,
ID_PROGRAM CHAR(5) NOT NULL REFERENCES PROGRAM
)
GO
--CATEGORY: CATEGORIA
CREATE TABLE CATEGORY(
ID_CATEGORY CHAR(5) NOT NULL PRIMARY KEY,
NAME_CATEGORY VARCHAR(80) NOT NULL,
ID_COURSE CHAR(5) NOT NULL REFERENCES COURSE
)
GO
--TOPIC _ TEMA
CREATE TABLE TOPIC(
ID_TOPIC CHAR(5) NOT NULL PRIMARY KEY,
NAME_TOPIC VARCHAR(150) UNIQUE NOT NULL
)
GO
--WEBINAR : SEMINARIO WEB
CREATE TABLE WEBINAR(
ID_WEB CHAR(5) NOT NULL PRIMARY KEY,
ID_TOPIC CHAR(5) NOT NULL REFERENCES TOPIC,
DURATION INT NOT NULL,
CHECK (DURATION>=1),
)
GO
--WEBINAR_USER : SEMINARIO WEB_ USUARIO
CREATE TABLE WEBINAR_USER(
ID_WEB CHAR(5) NOT NULL REFERENCES WEBINAR,
ID_USER CHAR(5) NOT NULL REFERENCES USS,
ID_SCHEDULE CHAR(5) NOT NULL REFERENCES SCHEDULE,
DETAIL VARCHAR(150) NULL
)


--CREAR INDICES
--INDICE QUE BUSCA CURSO POR DOCENTE 
CREATE INDEX IDX_COURSOPROF ON [dbo].[COURSE]([NAME_COURSE],[ID_PROFESSOR]) INCLUDE  ([ID_USER],[FIRST_NAME],[LAST_NAME]) 

--INDICE QUE BUSCA LOS WEBINARS QUE TENGA LA DURACION
CREATE INDEX IDX_WEBDUR ON  [dbo].[WEBINAR]([ID_TOPIC]) INCLUDE ([DURATION])

--INDICE QUE BUSCA LOS ALUMNOS Y SU DISCAPACIDAD
CREATE INDEX ICX_CODEM ON [dbo].[CODER](IMPAIRMENT) INCLUDE ([ID_CODER],[ID_USER])