USE MASTER
GO
CREATE DATABASE TAREA2
USE TAREA2
GO

--creacion de la tabla proveedor
CREATE TABLE PROVEEDOR
(
IDPROVEEDOR INT NOT NULL PRIMARY KEY,
NOMBRE_COMPAÑIA NVARCHAR(40) NOT NULL,
NOMBRE_CONTACTO NVARCHAR (30) NULL,
CARGO_CONTACTO NVARCHAR(30) NULL,
DIRECCION NVARCHAR (60) NULL,
CIUDAD NVARCHAR (15) NULL,
REGION NVARCHAR (15) NULL,
COD_POSTAL NVARCHAR (10) NULL,
PAIS NVARCHAR (15) NULL,
TELEFONO NVARCHAR (24) NULL,
FAX NVARCHAR (24) NULL,
PAGINA_PRINCIPAL NVARCHAR (16) NULL
)
GO
--CREACION DE LA TABLA VENDEDOR
CREATE TABLE VENDEDOR(
IDVENDEDOR INT NOT NULL PRIMARY KEY,
CIUDAD NVARCHAR (15) NULL,
REGION NVARCHAR (15) NULL,
COD_POSTAL NVARCHAR (15) NULL,
NOMBRE_VENDEDOR NVARCHAR (255) NULL
)
GO
--CREACION DE LA TABLA PEDIDO
CREATE TABLE PEDIDO(
IDPEDIDO INT NOT NULL PRIMARY KEY,
FECHA_PEDIDO DATETIME NULL,
FECHA_ENTREGA SMALLDATETIME NULL,
FECHA_ENVIO SMALLDATETIME NULL,
COMPANIA_ENVIO NVARCHAR (40) NULL
)

--AÑADIR COLUMNA FALTANTE EN PEDIDO
ALTER TABLE PEDIDO ADD IDPROVEEDOR INT NULL
ALTER TABLE PEDIDO ADD IDVENDEDOR INT NULL
SELECT * FROM PEDIDO


--ANADIR FK
ALTER TABLE [dbo].[PEDIDO]
ADD CONSTRAINT FK_PEDIDO_PROVEEDOR
FOREIGN KEY([IDPROVEEDOR])
REFERENCES PROVEEDOR([IDPROVEEDOR])
GO
ALTER TABLE [dbo].[PEDIDO]
ADD CONSTRAINT FK_PEDIDO_VENDEDOR
FOREIGN KEY([IDVENDEDOR])
REFERENCES [dbo].[VENDEDOR]([IDVENDEDOR])

