--REALIZACION DEL DEMO2_SEM2
USE MASTER
GO
CREATE DATABASE DEMO2_SEM2
GO
USE DEMO2_SEM2
GO

--CREAR TABLAS
CREATE TABLE ALUMNO(
CODALUMNO INT IDENTITY(1,1),
FECHAINSCRIPCION DATE NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL
)
GO
--CREAR TABLA CURSO
CREATE TABLE CURSO(
CODCURSO INT IDENTITY(1,1),
NOMBRECURS VARCHAR(50) NOT NULL,
FECHA_INI DATE NOT NULL,
FECHA_FINAL DATE NOT NULL,
COSTOCURSO MONEY NOT NULL
)
GO
--CREAR TB NOTA
CREATE TABLE NOTA(
CODNOTA INT IDENTITY(1,1),
CODALUMNO INT,
CODCURSO INT,
NOTA INT NOT NULL,
OBSERVACION VARCHAR(100) NOT NULL,
)
GO
--GEENERAR LLAVES PRIMARIA
/*
PK: IDENTIFICA DE FORMA UNICA AL CAMPO DE LA TB
SINTAXIS:
ALTER TABLE NOMBRE_TABLA
ADD CONSTRAINT PK_NOMBRE_TABLA
PRIMARY KEY(COLUMNAX,COMLUMNAY,..)
*/
ALTER TABLE ALUMNO
ADD CONSTRAINT PK_ALUMNO
PRIMARY KEY(CODALUMNO)
GO

ALTER TABLE CURSO
ADD CONSTRAINT PK_CURSO
PRIMARY KEY (CODCURSO)
GO 

ALTER TABLE NOTA
ADD CONSTRAINT PK_NOTA
PRIMARY KEY (CODNOTA)
GO

--CREACION LLAVE FORANEA
/*
FK: CLAVE EXTERNA, DEFINIDO RESTRICCION
SINTAXIS:
ALTER TABLE NOMBRE_TABLA
ADD CONSTRAINT FK_NOMBRE_TABLA_REFERENCIADA
FOREIGN KEY (COLUMNAX,COLUMNAZ,..)
REFERENCES (CODIGO_TABLA_REFERENCIADA)
*/

ALTER TABLE NOTA
ADD CONSTRAINT FK_NOTA_CURSO
FOREIGN KEY([CODCURSO])
REFERENCES CURSO([CODCURSO])
GO

ALTER TABLE NOTA
ADD CONSTRAINT FK_NOTA_ALUMNO
FOREIGN KEY([CODALUMNO])
REFERENCES ALUMNO([CODALUMNO])
GO

--RESTRICCION UNIQUE
/*
ESPECIFICA QUE 2 A MAS REGISTROS NO PUEDEN TENER EL MISMO VALOR
SINTAXIS:
ALTER TABLE NOMBRE_TABLA
ADD CONSTRAINT U_NOMBRE_TABLA_NOMBRE_COLUMNA
UNIQUE(COLUMNAP, COLUMNAX,...)
*/

--ASIGNAR UNIQUE AL CAMPO NOMBRE CURSO DE LATB CURSO
ALTER TABLE CURSO
ADD CONSTRAINT U_CURSO_NOMBRECURS
UNIQUE([NOMBRECURS])

--RESTRICCION DEFAULT
/*
CONOCIDO COMO UN VALOR PREDETERMINADO, DE MANERA AUTOMAICA ALMACENA EL CAMPO UN VALOR
SINTAXIS:
ALTER TABLE NOMBRE_TABLA
ADD CONSTRAINT DF_NOMBRE_TABLA_NOMBRE_COLUMNA
DEFAULT VALOR_PREDETERMINADO FOR COLUMNAX
*/

--ASIGNAR EL VALOR POR DEFECTO A LA COLUMNA FECHA INSCRIPCION
--DE LA TABLA ALUMNO
ALTER TABLE ALUMNO
ADD CONSTRAINT DF_ALUMNO_FECHAINSCRIPCION
DEFAULT GETDATE() FOR [FECHAINSCRIPCION]

--RESTRICCION CHEK
/*
REGLA DE VALIDACION, DAR A LA EXPRESION QUE EVALUE
LOS DATOS EN UNO O MÁS CAMPOS Y OFRECE UN VALOR
COMO VERDADERO O FALSO.
SINTAXIS:
ALTER TABLE NOMBRE_TABLA
ADD CONSTRAINT CHK_NOMBRE_TABLA_NOMBRE_COLUMNA
CHECK (CONDICION)
*/

--VALIDAR LOS DATOS DEL CAMPO NOTA DE LA TABLA NOTA
-- EN EL CAMPO NOTA SE INGRESARA SOLO 0 A 20
ALTER TABLE NOTA
ADD CONSTRAINT CHK_NOTA_NOTAS
CHECK(NOTA>=0 AND NOTA<21)

--INGRESAR DATOS A LA TABLAS DE LA BD DEMO2
--VISUALIZAR LA TABLA ALUMNO
SELECT * FROM ALUMNO
INSERT INTO ALUMNO(NOMBRES,APELLIDOS)VALUES('FREYO','SAMARITANO AYALA')
INSERT INTO ALUMNO(NOMBRES,APELLIDOS) VALUES('LUIS', 'SAMARITANO OLORTEGUI')
INSERT INTO ALUMNO(NOMBRES,APELLIDOS) VALUES('FLOR', 'AYALA ESPINOZA')
INSERT INTO ALUMNO(NOMBRES,APELLIDOS) VALUES('HAZAEL','DE LA CRUZ SAMARITANO')
INSERT INTO ALUMNO(NOMBRES,APELLIDOS) VALUES('YECHT','SAMARITANO AYALA')

--VSUALIZAR LA TABLA CURSO
SELECT * FROM CURSO

INSERT INTO CURSO VALUES('MODELAMIENTO DE DATOS','02/01/2021','03/02/2021','300')
INSERT INTO CURSO VALUES('IMPLEMENTACION DE DATOS','03/05/2021','04/04/2021','400')
INSERT INTO CURSO VALUES('ADMINISTRACION DE DATOS','03/03/2021','09/04/2021','400')
INSERT INTO CURSO VALUES('INTELIGENCIA DE NEGOCIOS','04-09-2021','05-09-2021','450')
INSERT INTO CURSO VALUES('BIG DATA','07/07/2021','08/24/2021',500)

--VISUALIZAR LA TABLA NOTA
SELECT * FROM NOTA
SELECT * FROM CURSO
SELECT * FROM ALUMNO
INSERT INTO NOTA (CODALUMNO,CODCURSO,NOTA,OBSERVACION)
VALUES (1, 1,20,'APROBADO')
INSERT INTO NOTA (CODALUMNO,CODCURSO,NOTA,OBSERVACION)
VALUES (2,2,18,'APROBADO')
INSERT INTO NOTA (CODALUMNO,CODCURSO,NOTA,OBSERVACION)
VALUES (3,4,10,'DESAPROBADO')
INSERT INTO NOTA (CODALUMNO,CODCURSO,NOTA,OBSERVACION)
VALUES (4,3,20,'APROBADO')
INSERT INTO NOTA (CODALUMNO,CODCURSO,NOTA,OBSERVACION)
VALUES (5,5,13,'APROBADO')

DELETE NOTA WHERE CODNOTA>5
--ACTUAIZAR LA TABLA ALUMNO
/*
UPDATE NOMBRE TABLA SET CAMPO1=VALOR1, CAMPO2=VALOR2 WHERE CAMPO = CONDICION
*/
SELECT * FROM ALUMNO
--DCL (LENGUAJE DE CONTROL DE DATOS-SGT CURSO)
UPDATE ALUMNO SET NOMBRES='JOSE' WHERE CODALUMNO=2
