USE MASTER
GO
CREATE DATABASE DEMO4_SEM2
GO
USE DEMO4_SEM2
GO

--CREACION DE LA TB CATGORIA
CREATE TABLE CATEGORIA(
COD_CAT CHAR(3) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL
)
GO

--CREACION TABLA DISTRITO
CREATE TABLE DISTRITO(
ID_DISTRITO CHAR(4) NOT NULL PRIMARY KEY,
NOMBRE_DISTRITO VARCHAR(40) UNIQUE NOT NULL
)
GO

--CREACION DE LA TABLA CARGO
CREATE TABLE CARGO(
COD_CARGO CHAR(3) NOT NULL PRIMARY KEY,
NOMBRE_CARGO VARCHAR(40) NOT NULL
)
GO

--CREAR TABLA EMPLEADOS
CREATE TABLE EMPLEADOS(
COD_EMPLE CHAR(5) NOT NULL PRIMARY KEY,
NOMBRES VARCHAR(25) NOT NULL,
APELLIDOS VARCHAR(30) NOT NULL,
DNI_EMPL CHAR(8) UNIQUE NOT NULL,
--DNI_EXT CHAR(20) UNIQUE NULL,
DIRECCION VARCHAR(60) NOT NULL,
ESTADO_CIVIL VARCHAR(1) NOT NULL,
NIVEL_EDUCA VARCHAR(40) NOT NULL,
TELEFONO CHAR(9) UNIQUE NOT NULL,
EMAIL VARCHAR(40) NOT NULL,
SUELDO_BASICO MONEY NOT NULL,
FECHA_INGRESO DATE NOT NULL,
ID_DISTRITO CHAR(4) NOT NULL REFERENCES DISTRITO,
COD_CARGO CHAR(3) NOT NULL REFERENCES CARGO
)
GO

--CREATE TABLA CLIENTE
CREATE TABLE CLIENTE(
ID_CLIENTE CHAR (6) NOT NULL PRIMARY KEY,
NOMBRES VARCHAR(40) NOT NULL,
APELLIDOS VARCHAR(40) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
FONO CHAR(9) NOT NULL,
ID_DISTRITO CHAR(4) NOT NULL REFERENCES DISTRITO,
EMAIL VARCHAR(40) NOT NULL
)
GO

--CREAR TABLA PRODUCTO
CREATE TABLE PRODUCTO(
ID_PRODUCTO CHAR(6) NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR(100) NOT NULL,
PRECIO_VENTA MONEY NOT NULL,
STOCK_MINIMO INT NOT NULL,
STIC_ACTUAL INT NOT NULL,
FECHA_VENC DATE NOT NULL,
COD_CAT CHAR(3) NOT NULL REFERENCES CATEGORIA
)
GO

--CREACION TABLA BOLETA
CREATE TABLE BOLETA(
NUM_BOLETA CHAR(8) NOT NULL PRIMARY KEY,
FECHA_EMI DATE NOT NULL,
ID_CLIENTE CHAR (6) NOT NULL REFERENCES CLIENTE,
COD_EMPLE CHAR(5) NOT NULL REFERENCES EMPLEADOS,
ESTADO_BOLETA VARCHAR(50) NOT NULL
)
GO

--CREACION DE LA TABLA DETALLE BOLETA
CREATE TABLE DETALLEBOLETA(
NUM_BOLETA CHAR(8) NOT NULL REFERENCES BOLETA,
ID_PRODUCTO CHAR(6) NOT NULL REFERENCES PRODUCTO,
CANTIDAD INT NOT NULL,
IMPORTE MONEY NOT NULL,
PRIMARY KEY (NUM_BOLETA, ID_PRODUCTO)
)
GO

--ASIGNAR A LA TABLA CLIENTE EL NO REGISTRO AL CAMPO EMAIL
ALTER TABLE CLIENTE
ADD CONSTRAINT DF_EMAIL
DEFAULT 'NO REGISTRA' FOR EMAIL


--ASIGNAR EL VALOR "000000000" AL CAMPO FOONO DE LA TB CLIENTE
ALTER TABLE CLIENTE
ADD CONSTRAINT DF_FONO
DEFAULT '000000000' FOR FONO

--ASIGNAR AL PROCIO DE VENTA DEBE SER MAYOR A 0 DE LA TB PRODUCTO
ALTER TABLE PRODUCTO
ADD CONSTRAINT CHK_PRECIOVENTA
CHECK ([PRECIO_VENTA]>0)

--ASIGNAR AL ESTADO BOLETA SOLO DE PERMISO ACTIVO(AC) Y ANULADO (AN)
ALTER TABLE BOLETA
ADD CONSTRAINT CHK_ESTADO
CHECK([ESTADO_BOLETA] IN ('AC','AN'))

--ASIGNAR A LA FECHA DE EMISION DEBE ER MAYOR A LA FECHA ACTUAL DE LA BOLETA
ALTER TABLE BOLETA
ADD CONSTRAINT CHK_FECHAEMI
CHECK ([ESTADO_BOLETA]>=GETDATE())

--ASIGNAR AL CAMPO ESTADO CIVIL DE LA TABLA EMPLEADOS SOLO DEBE PERMITIR VALORES 
-- C DE CASADO Y S DE SOLTERO, T CONVIVIENDE, D DIVORCIADO, V VIUDO
ALTER TABLE [dbo].[EMPLEADOS]
ADD CONSTRAINT CHK_ESTADOCIVIL
CHECK([ESTADO_CIVIL] IN ('C', 'T', 'S', 'D', 'V') )

--ASIGNAR AL CAMPO DE NIVEL DE EDUCACION DE TB EMPLADO SOLO DEBE PERMITIR LOS VALORES
-- PRIMARIA, SECUNDARIA, SUPERIOR, UNIVERSITARIA
ALTER TABLE [dbo].[EMPLEADOS]
ADD CONSTRAINT CHK_NIVELEDUCA
CHECK ([NIVEL_EDUCA] IN( 'PRIMARIA', 'SECUNDARIA', 'SUPERIOR','UNIVERSITARIA') )

--ASIGNAR AL CAMPO SUELDO BASICO EL VALOR DE 9.50 DE LA TB EMPLEADO
ALTER TABLE [dbo].[EMPLEADOS]
ADD CONSTRAINT CHK_SUELDO
CHECK ([SUELDO_BASICO]>=950.00)

--CONSULTAR LAS RESTRICCIONES
GO
SP_HELPCONSTRAINT BOLETA
GO
SP_HELPCONSTRAINT EMPLEADO
GO
SP_HELPCONSTRAINT PRODUCTO
GO
--LISTAR LOS CAMPOS DE LAS TABLAS
SP_COLUMNS BOLETA
GO
SP_COLUMNS CARGO
GO
SP_COLUMNS CLIENTE
GO
SP_COLUMNS CATEGORIA
GO
SP_COLUMNS DETALLEBOLETA
GO
SP_COLUMNS DISTRITO
GO
SP_COLUMNS EMPLEADOS
GO
SP_COLUMNS PRODUCTO

--asignar A LA TABLA CLIENTE EL NO REGISTRAR AL CAMPO EMAIL
--ALTER TABLE CLIENTE
--ADD CONSTRAINT CHK_EMAIL
