--creacion de un BD DEMO_SEM2_1
--BD SIN DEFINICION
CREATE DATABASE DEMO_SEM2_1
GO
USE DEMO_SEM2_1
GO

--CREACION DE LA TABLA ALUMNO
CREATE TABLE ALUMNO(
CODIGOALU INT NOT NULL,
NOMBRE VARCHAR(30) NOT NULL,
APELLIDOS VARCHAR(40) NOT NULL,
EDAD INT NOT NULL,
DIRECCION VARCHAR(50) NOT NULL
)
GO
--AGEGAR UNA COLUMNA A LA TABLA
ALTER TABLE ALUMNO 
ADD FECHAINSCRIP DATE NOT NULL
GO
--SE DESEA MODIFICAR EL TIPO DE DATO DE LA COLUMNA NOMBRE DE LA TB ALUMNO
ALTER TABLE ALUMNO
ALTER COLUMN NOMBRE NVARCHAR(100) NOT NULL
GO
--ELIINAR LA COLUMNA FECHA INSCRIPCION DE LA TB ALUMNO
ALTER TABLE ALUMNO
DROP COLUMN FECHAINSCRIP

--VISUALIZAR MI TB CAMBIO TB ALUMNO
SELECT * FROM ALUMNO
GO
--VALOR AUTOGENRADO
/*
IDENTITY CREA UN VALOR SECUENCIAL
*/
ALTER TABLE ALUMNO
DROP COLUMN CODIGOALU

--AGREGAR INCREMENTO
ALTER TABLE ALUMNO
ADD CODIGOALU INT IDENTITY (1,1) NOT NULL

--INSERTAR REGISTOS VALUES 
INSERT INTO ALUMNO VALUES ('LESLY', 'SAMARITANO AYALA', 25, 'AV. QUECHUAS 516')
INSERT INTO ALUMNO VALUES ('FLOR', 'AYALA ESPINOZA', 40, 'AV. CHANCAS 50')

--ELIMINAR REGISTROS
/*
SINTAXIS
DELETE NOMBRE_TABLA WHERE CAMPO=CONDICION
*/
DELETE ALUMNO WHERE CODIGOALU>1
GO